### ISSUE TITLE
Defining support strategy for more than one classes does't support

### ISSUE THREAD

**Issue by psuhane** [YouweGit/pimcore-workflow-gui#11]
Workflow configuration can be defined in YML config for more than one classes but GUI doesn't support this.

supports:
       - Pimcore\Model\DataObject\Product
       - Pimcore\Model\DataObject\ProductCategory

**Comment by dpfaffenbauer** [comment]
will fix that

**Comment by jorisros** [comment]
@vmalyk thank you for the pullrequest
