### ISSUE TITLE
Restricting space in Workflow name

### ISSUE THREAD

**Issue by amarjeet6694** [YouweGit/pimcore-workflow-gui#14]
I created a new workflow through WorkflowGUI and named it "**Products Workflow**" and did all the settings correctly and was working fine.

But when I opened an object and navigated to **Workflow Tab** (in between Tags and Children Grid tab), I was unable to see **Workflow Graph**

Possible reason 
To show Workflow Graph Pimcore executes following Command
**_php /var/www/html/standard/demos/bin/console pimcore:workflow:dump Products Workflow accepted | /usr/bin/dot -Tsvg_**

**If I rename the Workflow name to product_workflow or any name w/o spaces, the graph was visible.**

**Comment by dpfaffenbauer** [comment]
not a gui issue, thats a pimcore thing. Please report that to pimcore
