### ISSUE TITLE
Roles were not coming up in the Notify Roles dropdown.

### ISSUE THREAD

**Issue by amarjeet6694** [YouweGit/pimcore-workflow-gui#15]
So, I was doing Notification settings in the WorkflowGUI and for some reason, Roles were not coming up in the **Notify Roles** dropdown.

Also after creating Notification setting, I try to save the Workflow, I was getting the following error
message:"**Unrecognized option "notifyRules" under "pimcore.workflows.product_workflow.transitions.content_review.options.notificationSettings.0**""
success:false

While traversing through code (/_youwe/workflow-gui/src/WorkflowGui/Resources/public/js/pimcore/workflow/transition_notification.js_), you used "**notifyRules**" instead of "**notifyRoles**" in creating Roles combobox.

**Comment by dpfaffenbauer** [comment]
👍 can you create a PR for that?

**Comment by jorisros** [comment]
Also the query is wrong for receiving roles. I make a pull request for this.

**Comment by dpfaffenbauer** [comment]
🎉

**Comment by jorisros** [comment]
Issue seemed to be solved
