### ISSUE TITLE
Background-color value for label is missing "#"

### ISSUE THREAD

**Issue by dgalezow** [YouweGit/pimcore-workflow-gui#20]
Hi, I have Pimcore v5.6.3

Background-color and border value in style for label is missing "#" so its ignored. Html code for label looks like this:
`<div class="pimcore-workflow-place-indicator" style="background-color: 53c5cc; color:#ffffff; border: 1px solid 53c5cc;" title="New Title">
            New Label
        </div>`

**Comment by dpfaffenbauer** [comment]
yes, nothing we can do except maybe some input validation. Please use it with #.

**Comment by dgalezow** [comment]
@dpfaffenbauer  
There is no way to manually input it with #
You have to choose color with color-picker and it sets input value without #

**Comment by dpfaffenbauer** [comment]
ah ok. I will reopen the issue then

**Comment by jorisros** [comment]
The problem is that the colorpicker in the UI don't need that '#' symbol, so have to make a workaround for it.
