### ISSUE TITLE
Change channelType to pimcoreNotification is not possible

### ISSUE THREAD

**Issue by judip** [YouweGit/pimcore-workflow-gui#41]
Is not possible change channelType from "mail" to "pimcoreNotification" method. There is no button, field or checkbox to switch it. "Mail" is default method for notifications.

**Comment by jorisros** [comment]
We should implement the new option of the workflow engine, added in this commit https://github.com/pimcore/pimcore/commit/fd36e47442027300f04052325ae9d475b693d63b

**Comment by Yivan** [comment]
Hello,

Same here, would be great to have a select for channelType.
If mail is the default, so notifications cannot be send actually I imagine. And if this is the case, this is a very usefull feature.

I hope it could be added.

Thanks.

**Comment by jorisros** [comment]
@vmalyk thank you for pullrequest !!!
