### ISSUE TITLE
support_strategy service seems to have problem with autoload

### ISSUE THREAD

**Issue by Yivan** [YouweGit/pimcore-workflow-gui#43]
Hello,

Just trying to copy the default demo Pimcore workflow `product_data_enrichment` (https://github.com/pimcore/demo/blob/master/app/config/workflows.yml) into the workflow.yml file used by workflow GUI and open it on Workflow GUI.
It won't open (error JS triggered by PHP error).

It use:

```
            support_strategy:
                service: AppBundle\Workflow\SupportsStrategy
```

When opening the workflow on Workflow GUI we get:
`The service "workflow.registry" has a dependency on a non-existent service "AppBundle\Workflow\SupportsStrategy".`

Tried with `\AppBundle\Workflow\SupportsStrategy` (first backslash) too, same.

Thanks.

**Comment by jorisros** [comment]
@Yivan Did you have the demo installed? when you have the demo installed there is that service available. I tried with pimcore 10.2.8  and version 2.0.1 of this bundle. And everything seems fine and working

**Comment by Yivan** [comment]
Yes it was on the demo if I remember.
Maybe it has been fixed the time during.
Greats if it works now!
Thanks.
