### ISSUE TITLE
Provide Video demo for usage

### ISSUE THREAD

**Issue by rajesh17692** [YouweGit/pimcore-workflow-gui#49]
Hello Team,

Please provide a video demo of how we can use this with our class and hot to configure as I am not getting any clue or success about usage.

**Comment by dpfaffenbauer** [comment]
No

**Comment by rajesh17692** [comment]
But why demo of how to use can not be provided

**Comment by dpfaffenbauer** [comment]
Cause no one pays me to make a video. Open source does not mean free work. You can’t just ask for things and assume you get it!

**Comment by rajesh17692** [comment]
I am asking for in general-purpose not for specific to me like you can add GIF of usage in readme doc.

So that your bundle can be useful without knowing how this bundle will how general public can use this bundle.

**Comment by dpfaffenbauer** [comment]
The General Public knows!

**Comment by rajesh17692** [comment]
I don't know

**Comment by dpfaffenbauer** [comment]
This bundle exists for couple of years now and never had anyone a problem to not understand it.

And even if, I would not create a video unless someone pays me to do so!

**Comment by rajesh17692** [comment]
OK let it be if you don't want to share your knowledge.
