### ISSUE TITLE
Not working with Pimcore 6.8

### ISSUE THREAD

**Issue by rajesh17692** [YouweGit/pimcore-workflow-gui#50]
Installed in Pimcore 6.8
Installed followed steps when saving values of default pimcore workflow in the file it's working
but when generating or modified data from UI then getting below error when opening object

![image](https://user-images.githubusercontent.com/32155962/96997721-eb58d800-154f-11eb-8954-7b9669387ba9.png)

**Comment by rajesh17692** [comment]
When added below configuration directly in workflow.yml it worked as expected but when update files value from GUI then getting above error on the opening of the object


pimcore:
  workflows:
    product:
      enabled: true
      priority: 1
      label: 'Product Workflow'
      initial_place: new
      type: state_machine
      supports:
        - 'Pimcore\Model\DataObject\Product'
      places:
        new:
          label: 'New product'
          color: '#377ea9'
          permissions:
            -   objectLayout: 1
        rejected:
          label: 'Rejected product'
          color: '#28a013'
        update_content:
          label: 'Update Content'
          title: 'Updating content step'
          color: '#d9ef36'
          permissions:
            -   objectLayout: 2
          visibleInHeader: true
        update_picture:
          label: 'Update Product Picture'
          title: 'Update the product picture'
          color: '#d9ef36'
          permissions:
            -   objectLayout: 2
        validate_stock_and_price:
          label: 'Validate Stock + Price'
          title: 'Check the quantity and the price'
          color: '#d9ef36'
          permissions:
            -   objectLayout: 2
        content_prepared:
          label: 'Content Prepared'
          title: 'Content ready to publish'
          color: '#28a013'
        accepted:
          label: 'Accepted product'
          color: '#28a013'
      transitions:
        reject_product:
          from: [ new, content_prepared ]
          to: rejected
          options:
            label: 'Reject the product'
            notes:
              commentEnabled: true
              commentRequired: true
        start_processing:
          from: [ new, content_prepared ]
          to: update_content
          options:
            label: 'Start processing the product'
            notes:
              commentEnabled: true
              commentRequired: false
        content_updated:
          from: update_content
          to: update_picture
          options:
            label: 'Content up-to-date'
            notes:
              commentEnabled: true
              commentRequired: false
        picture_updated:
          from: update_picture
          to: validate_stock_and_price
          options:
            label: 'Picture up-to-date'
            notes:
              commentEnabled: true
              commentRequired: false
        content_ready:
          from: validate_stock_and_price
          to: content_prepared
          options:
            label: 'Content is ready to publish'
        publish:
          from: content_prepared
          to: accepted
          guard: "is_fully_authenticated() and has_role('ROLE_PIMCORE_SUPERUSER')"
          options:
            label: 'Publish the product'
            notes:
              additionalFields:
                -   name: 'timeWorked'
                    fieldType: 'input'
                    title: 'Time Spent'
                    required: true

**Comment by dpfaffenbauer** [comment]
I just installed and used it with 6.8, so it is working fine...

**Comment by rajesh17692** [comment]
Have you checked with the configuration which I provided above which I got when saving workflow GUI?
Please check once with the above configuration.
