### ISSUE TITLE
pimcore Uncaught ReferenceError: service is not defined

### ISSUE THREAD

**Issue by benstinton** [YouweGit/pimcore-workflow-gui#55]
Thank-you very much for your extension. 

When you use 'service' as a support strategy, you are unable to re-open a workflow for editing, this is the message that pops up. I've tracked the issue down to ln 430 of item.js

`supportType = service;` should be `supportType = 'service';`

Do you need me to create a pull request? Or as it a minor edit, can you fix your end?

**Comment by dpfaffenbauer** [comment]
PR please

**Comment by benstinton** [comment]
@dpfaffenbauer Thats done ☝️

**Comment by dpfaffenbauer** [comment]
thanks, 1.3.6 has been tagged
