### ISSUE TITLE
support pimcore 10

### ISSUE THREAD

**Issue by ismetsener** [YouweGit/pimcore-workflow-gui#57]
Hi,
when will   "YouweGit / pimcore-workflow-gui "  be available for Pimcore 10 ?

with kind regards,
Ismet

**Comment by dpfaffenbauer** [comment]
whenever someone decides to make a PR for it... I don't have time for that now.

**Comment by jorisros** [comment]
Still it is a issue to solve, so i dont think it is a good idea to close the issue. 

So me or some else at Youwe can solve this issue, closing issues like this is not a positive signal.

**Comment by dpfaffenbauer** [comment]
I don't see it as an issue, I see it as a necessity. It already is on my todo list, but there are lots of other plugins with a higher priority to do first.

**Comment by jorisros** [comment]
Great, as always love your commitment. 

Was already working on this plugin to make it compatible/working on X. Let me know if I should put more effort in it or you will pick it up.
