### ISSUE TITLE
workflow.yml  missing

### ISSUE THREAD

**Issue by ismetsener** [YouweGit/pimcore-workflow-gui#59]
Hi, 
I have installed YouweGit / pimcore-workflow-gui:
composer require youwe/workflow-gui dev-master -W

but I have problem with this step:
Make sure that the Bundles generated config is loaded (config/config.yaml): ../var/bundles/workflow-gui/workflow.yml

I cannot find this file: workflow.yml

regards,
Ismet

**Comment by dpfaffenbauer** [comment]
The file is not generated when you install the plugin. You have to create a workflow first or create the file manually.

**Comment by ismetsener** [comment]
> The file is not generated when you install the plugin. You have to create a workflow first or create the file manually.

But i do not see the WORKFLOW  in the settings menu, so how can I create the file?

**Comment by jorisros** [comment]
To prevent this question in the further I added a example file in the README as documentation
