### ISSUE TITLE
I do not see the workflow in the system settings menu

### ISSUE THREAD

**Issue by ismetsener** [YouweGit/pimcore-workflow-gui#60]
Hello,

I installed youwe/workflow-gui
but I do not see the workflow in the system settings menu
https://github.com/YouweGit/pimcore-workflow-gui/issues/59#issuecomment-865741430

**Comment by ismetsener** [comment]
problem solved by upgrading pimcore-10.0.4  to 10.0.x-dev

**Comment by jorisros** [comment]
problem seems to be solved in 10.2.8
