### ISSUE TITLE
Symfony\Component\Process\Process::fromShellCommandline(): Argument #1 ($command) must be of type string, null given, 

### ISSUE THREAD

**Issue by ismetsener** [YouweGit/pimcore-workflow-gui#65]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no
| Branch?          | master

After upgrading to 10.2.5   I go this error::
Symfony\Component\Process\Process::fromShellCommandline(): Argument #1 ($command) must be of type string, null given, called in /opt/pimcore/vendor/youwe/workflow-gui/src/WorkflowGui/Controller/WorkflowController.php on line 345

before the upgrade I could see the VISUAL STEPS

**Comment by Stefan-JustMe69-SQ** [comment]
same with 10.2.7

**Comment by jorisros** [comment]
This is caused by the reason that the workflow is not 'enabled' and there for not available in as container. When you enable the flow the graph will be available.

**Comment by ismetsener** [comment]
Dear Joris,

It is anabled;
(CORS-WORKFLOW-GUI-2.01
![image](https://user-images.githubusercontent.com/72578924/149125509-5b31f90d-4b88-4ff8-93dc-734f0bd61654.png)

![image](https://user-images.githubusercontent.com/72578924/149125631-c9966014-ea7c-4a8d-ad72-70bccb75e3ab.png)

**Comment by jorisros** [comment]
@ismetsener thank you for the clarification, after my comment i found that in Pimcore 10.2.x is calling a depreciated command. '$cmd = Console::addLowProcessPriority($cmd);' (which was working on Pimcore 6.* perfectly) in my pullrequest i removed that and it seem to be that it now working correctly

**Comment by ismetsener** [comment]
which I have to use?

"cors/workflow-gui": "^2.0.1",
"youwe/workflow-gui":"^2.0.0",

`I, Dominik (@pfaffenbauer), will stop maintaining this form now on and will continue to work on this fork https://github.com/cors-gmbh/pimcore-workflow-gui`

so I used the new one "cors/workflow-gui": "^2.0.1",


But  I just tried both versions, and it did not work
I have to wait for new version/updtae?

**Comment by jorisros** [comment]
At the moment i am in the process of doing a new release where this problem should be fixed. see pull request #66, when that pullrequest is merged then i will trigger a new release.

**Comment by ismetsener** [comment]
Thank you Joris,

in which ?
 "cors/workflow-gui": "^2.0.1",
"youwe/workflow-gui":"^2.0.0",

**Comment by jorisros** [comment]
In the package "youwe/workflow-gui":"^2.0.0"

**Comment by jorisros** [comment]
@ismetsener there is now in youwe/workflow-gui a new release ready that should be solving this problem. Could you test if it works?

**Comment by ismetsener** [comment]
it works :)
thank you Joris

**Comment by jorisros** [comment]
@ismetsener Thank you for testing.
