### ISSUE TITLE
A delete button to different grids

### ISSUE THREAD

**Issue by jorisros** [YouweGit/pimcore-workflow-gui#7]
We need to have the ability to delete functionality on the following grids:
- [x] Places
- [x] Transitions
- [x] Global actions
- [x] Place -> Permissions
- [x] Transitions -> Notifications

**Comment by dpfaffenbauer** [comment]
Places:
<img width="1050" alt="bildschirmfoto 2019-01-03 um 18 37 20" src="https://user-images.githubusercontent.com/5981845/50652364-9f0d6400-0f86-11e9-8d32-53d0778459fd.png">

Transitions:
<img width="1105" alt="bildschirmfoto 2019-01-03 um 18 37 34" src="https://user-images.githubusercontent.com/5981845/50652374-a59bdb80-0f86-11e9-8f74-450b6ea9469c.png">

Global Actions:
<img width="1068" alt="bildschirmfoto 2019-01-03 um 18 37 46" src="https://user-images.githubusercontent.com/5981845/50652385-adf41680-0f86-11e9-9c9b-2e2cf0c8e973.png">

Place -> Permissions:
<img width="619" alt="bildschirmfoto 2019-01-03 um 18 37 59" src="https://user-images.githubusercontent.com/5981845/50652403-b8161500-0f86-11e9-9191-e0d7f62b4755.png">

Transition -> Notification:
<img width="620" alt="bildschirmfoto 2019-01-03 um 18 38 22" src="https://user-images.githubusercontent.com/5981845/50652421-c49a6d80-0f86-11e9-8f18-f77161678567.png">
